[pytest]

markers = 
    smoke: Smoke Testing Test Cases
    regression: Regresion testing Test Cases
    test:  Test env test cases
    prod:   Prod env test cases
    preprod: Preprod env TC
    smoke1: Testing purpose
    smoke2: Smoke Testing Test Cases in Test 2 Env
    regression2: regression in Test 2 Env
    smoke4: Smoke Testing Test Cases in Test 3 Env